config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  devise_for :users

  root to: "pages#home"

  get "/évènements/:id/chat", to: 'events#chat', as: "chat"

  resources :boardgames, only: [] do
    collection do
      get :search
      get :select
    end
  end

  get "/profil/mes-demandes", to: 'users#my_inscriptions', as: "mes-demandes"
  get "/profil/mes-évènements", to: 'users#my_events', as: "mes-evenements"

  resources :inscriptions, only: %i[update]

  resources :users, only: %i[show edit update], path: "profil", param: :username

  resources :events, only: %i[index show new create], path: "évènements" do
    resources :inscriptions, only: %i[create], path: "inscription"
    resources :messages, only: %i[create], path: "messages"
    resources :boardgames_lists, only: %i[create], path: "boardgames"
  end

  resources :boardgames, only: %i[index show], path: "jeu-de-société", param: :name




  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
require 'open-uri'

class User < ApplicationRecord
  has_one_attached :photo

  has_many :my_events, class_name: 'Event', foreign_key: 'user_id', dependent: :destroy

  has_many :inscriptions, dependent: :destroy
  has_many :requests, through: :my_events, source: :inscriptions, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :events, through: :inscriptions, source: :event, dependent: :destroy

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :age, presence: true
  validates :city, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :generate_initials_image

  def generate_initials_image
    image = Cloudinary::Uploader.upload("https://fakeimg.pl/150x150/cccccc/?text= ",
                                        public_id: "user_#{id}_initials",
                                        transformation: [
                                          { width: 150, height: 150, gravity: "center", crop: "fill" },
                                          { overlay: "text:Arial_60_bold:#{initials}", gravity: "center", color: "white" }
                                        ])

    self.photo.attach(io: URI.open(image["secure_url"]), filename: "user_#{id}_initials.png")
  end
  #  "https://via.placeholder.com/150x150.png?text=#{initials}"
  #  "https://placehold.co/150/png?text=#{initials}"
  private

  def initials
    "#{first_name[0].upcase}#{last_name[0].upcase}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show]

  def show
    @user = User.find_by(username: params[:username])
    @display = super_current_user?(@user)
  end

  def my_inscriptions
    @requests = current_user.requests.where(status: "En attente")
    @processed_requests = current_user.requests.where(status: ["Validée", "Rejetée"])

    @inscriptions = current_user.inscriptions.where(status: "En attente")
    @processed_inscriptions = current_user.inscriptions.where(status: ["Validée", "Rejetée"])
  end

  def my_events
    @my_events = current_user.my_events
    @events = current_user.events
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user.username), notice: 'Profile image updated successfully.'
    else
      render :edit
    end
  end

  private

  def super_current_user?(user)
    user == current_user ? "" : "d-none"
  end

  def user_params
    params.require(:user).permit(:photo)
  end
end

app/views/users/my_events.html.erb
<div class= "btn-switch" >
    <%= link_to "Mes demandes", mes_demandes_path, class: "link_to", id: "request"%>
    <%= link_to "Mes évènements", mes_evenements_path, class: "link_to", id: "event"%>
</div>


<div class="bgm-container">
  <h2>Mes évènements</h2>
  <% @my_events.each do |event| %>
    <%= render partial: "events/card", locals: { event: event, show_event_creator: false } %>
  <% end %>


  <h2>Mes inscriptions</h2>
  <% @events.each do |event| %>
    <%= render partial: "events/card", locals: { event: event, show_event_creator: true } %>
  <% end %>
</div>

app/views/users/my_inscriptions.html.erb
<div class= "btn-switch" >
    <%= link_to "Mes demandes", mes_demandes_path, class: "link_to", id: "requests"%>
    <%= link_to "Mes évènements", mes_evenements_path, class: "link_to", id: "events"%>
</div>

<div class="bgm-container">


    <div class="block-margin"><h2>Reçues</h2></div>
    <!-- inscriptions reçues -->
    <div class="block-margin infos">
      <% if @requests.empty? %>
        <p>Aucune demande en attente</p>
      <% else %>
      <h4>En attente</h4>
        <% @requests.each do |request| %>
          <div class="inscription-card">
            <div class="title-card">
              <h4><%= request.event.title %></h4>
            </div>
            <div class= "content-card">

      <%= link_to user_path(request.user.username), class: "link_to" do %>
        <div class="event-creator">
          <div>
            <p><%= request.user.username %></p>
          </div>
          <div>
            <%= cl_image_tag(request.user.photo.key, class: "avatar") %>
          </div>
        </div>
      <% end %>
              <p><%= request.comment %></p>
              <div class="btn-inscription">
                <h4><%= link_to "Accepter", inscription_path(request, status: "Validée"), data: { controller: "inscriptions", turbo_confirm: "Voulez-vous vraiment accepter", turbo_method: :patch}, id: "accept" %></h4>
                <h4><%= link_to "Refuser", inscription_path(request, status: "Rejetée"), data: { controller: "inscriptions", turbo_confirm: "Voulez-vous vraiment refuser", turbo_method: :patch}, id: "reject" %></h4>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <% if @processed_requests.present? %>
      <div class="block-margin">

          <% @processed_requests.each do |request| %>
<div class="inscription-card">
            <div class="title-card">
              <h4><%= request.event.title %></h4>
            </div>
            <div class= "content-card">

      <%= link_to user_path(request.user.username), class: "link_to" do %>
        <div class="event-creator">
          <div>
            <p><%= request.user.username %></p>
          </div>
          <div>
            <%= cl_image_tag(request.user.photo.key, class: "avatar") %>
          </div>
        </div>
      <% end %>
              <p><%= request.comment %></p>
              <div id=<%= request.status == "Rejetée" ? "declined" : "accepted" %> class="statut"><%= request.status %></div>
            </div>
          </div>

          <% end %>

      </div>
    <% end %>


    <h2>Envoyées</h2>
    <!-- inscriptions envoyées -->
    <div class="infos block-margin">
      <% if @inscriptions.empty? %>
        <p>Aucune demande en attente</p>
      <% else %>
          <h4>En attente</h4>

          <% @inscriptions.each do |inscription| %>
<div class="inscription-card">
            <div class="title-card">
              <h4><%= inscription.event.title %></h4>
            </div>
            <div class= "content-card">

      <%= link_to user_path(inscription.event.creator.username), class: "link_to" do %>
        <div class="event-creator">
          <div>
            <p><%= inscription.event.creator.username %></p>
          </div>
          <div>
            <%= cl_image_tag(inscription.event.creator.photo.key, class: "avatar") %>
          </div>
        </div>
      <% end %>
              <p><%= inscription.comment %></p>

            </div>
          </div>
          <% end %>

      <% end %>
    </div>

    <% if @processed_inscriptions.present? %>
      <div>

          <% @processed_inscriptions.each do |inscription| %>
<div class="inscription-card">
            <div class="title-card">
              <h4><%= inscription.event.title %></h4>
            </div>
            <div class= "content-card">

      <%= link_to user_path(inscription.event.creator.username), class: "link_to" do %>
        <div class="event-creator">
          <div>
            <p><%= inscription.event.creator.username %></p>
          </div>
          <div>
            <%= cl_image_tag(inscription.event.creator.photo.key, class: "avatar") %>
          </div>
        </div>
      <% end %>
              <p><%= inscription.comment %></p>
              <div id=<%= inscription.status == "Rejetée" ? "declined" : "accepted" %> class="statut"><%= inscription.status %></div>
            </div>

          <% end %>

      </div>
    <% end %>

</div>

app/views/users/show.html.erb
<div class="bgm-container">
  <div class="user-id-card">
    <div class="full-id">
        <div class="full-name">
          <h5><%= @user.first_name %> <%= @user.last_name %></h5>
        </div>
        <p><%= @user.username %></p>
      </div>
      <%= cl_image_tag(@user.photo.key, class: "avatar-large") %>

      <div data-controller="edit">
        <i class="fa-solid fa-pen-to-square edit edit-img <%= @display %>" data-edit-target="btn" data-action="click->edit#selectImg"></i>
        <%= form_for @user, url: user_path(@user), html: { multipart: true, id: "edit-image-form", style: "display: none" }, data: { edit_target:"form"} do |f| %>
          <%= f.file_field :photo, accept: 'image/*', class: 'form-control', data: { edit_target: "input", action: "change->edit#upload" } %>
          <%= f.submit "Upload Image", class: "btn btn-primary" %>
        <% end %>
      </div>

  </div>
  <div class="informations block-margin">
    <div class="infos-color block-margin">
      <ul>
        <li>Membre depuis 2024 </li>
        <li> 3 évènements créés</li>
        <li>Participation à 5 évènements</li>
      </ul>
    </div>

    <div class="infos block-margin">

      <h4 class="user-info">🎂 <%= @user.age %></h4>

      <h4 class="user-info mt-4">🏠 <%= @user.city %></h4>

    </div>
  </div>
  <div class="block-margin">
  </div>
    <h2>Jeux préférés</h2>
      <div class="bg-cards block-margin">
      <% @user.my_events.first.boardgames.each do |boardgame| %>
        <%= link_to boardgame_path(boardgame.name) ,class: "link_to" do %>
          <%= render partial: "boardgames/card", locals: { close: false, boardgame: boardgame} %>
        <% end %>
      <% end %>
  </div>
  <%if @user == current_user%>
    <h2>Mes évèvements</h2>
  <% else %>
    <h2>Evènements de <%= @user.first_name %></h2>
  <% end %>
    <% @user.my_events.each do |event| %>
      <%= render partial: "events/card", locals: { event: event, show_event_creator: false } %>
    <% end %>


    <%# <%= simple_form_for(@user) do |f| %>
    <!-- [...] -->
    <%# <%= f.input :photo, as: :file %>
    <!-- [...] -->
    <%# <% end %>
</div>