config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  devise_for :users

  root to: "pages#home"

  get "/évènements/:id/chat", to: 'events#chat', as: "chat"

  resources :boardgames, only: [] do
    collection do
      get :search
      get :select
    end
  end

  get "/profil/mes-demandes", to: 'users#my_inscriptions', as: "mes-demandes"
  get "/profil/mes-évènements", to: 'users#my_events', as: "mes-evenements"

  resources :inscriptions, only: %i[update]

  resources :users, only: %i[show edit update], path: "profil", param: :username

  resources :events, only: %i[index show new create], path: "évènements" do
    resources :inscriptions, only: %i[create], path: "inscription"
    resources :messages, only: %i[create], path: "messages"
    resources :boardgames_lists, only: %i[create], path: "boardgames"
  end

  resources :boardgames, only: %i[index show], path: "jeu-de-société", param: :name




  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'

  has_many :boardgames_lists, dependent: :destroy
  has_many :boardgames, through: :boardgames_lists, dependent: :destroy
  has_many :inscriptions, dependent: :destroy
  has_many :participants, through: :inscriptions, source: :user
  has_many :messages, dependent: :destroy
  has_many :users, through: :inscriptions

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :address, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :date, presence: true
  validates :time, presence: true

  before_save :set_city

  geocoded_by :address

  after_validation :geocode, if: :will_save_change_to_address?

  private

  def set_city
    self.city = address.split(',')[-2].split(' ', 2)[1].strip
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index

    @events = Event.all

    if params[:search].present?
      @events = @events.where("city ILIKE ?", "%#{params[:search][:city]}%") if params[:search][:city].present?
      @events = @events.where("date::text ILIKE ?", "%#{params[:search][:date]}%") if params[:search][:date].present?
      @events = @events.joins(:boardgames).where("boardgames.name ILIKE ?", "%#{params[:search][:boardgame]}%") if params[:search][:boardgame].present?
    end

    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {event: event}),
        marker_html: render_to_string(partial: "marker", locals: {event: event})
      }
    end
  end

  def show
    @event = Event.find(params[:id])
    @inscription = Inscription.new
  end

  def new
    @event = Event.new
    @boardgames = Boardgame.all
  end

  def create
    @event = Event.new(event_params)
    @event.boardgames << Boardgame.where(id: params[:event][:boardgame_ids].split(","))
    @event.creator = current_user
    if @event.save
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity, locals: { event: @event }
    end

  end

  def chat
    @event = Event.find(params[:id])
    @message = Message.new
  end


  private

  def event_params
    params.require(:event).permit(:title, :description, :address, :date, :time, :capacity, :longitude, :latitude)
  end

end

app/views/events/_card.html.erb
<div class="block-margin">


    <div class="card-event">
      <%= link_to event_path(event), class:"link-to" do %>
        <div class='event-infos'>
          <div class="title">
            <h2><%= event.title %></h2>
          </div>
        </div>
        <div class="elements">
            <h4><i class="fa-solid fa-user-group"></i> <%= event.capacity %></h4>
            <h4><i class="fa-solid fa-calendar"></i>  <%= event.date.strftime("%d-%m-%y") %></h4>
            <h4><i class="fa-solid fa-location-dot"></i>  <%= event.city %></h4>
          </div>
      <% end %>

    <div class="bg-cards">
      <% event.boardgames.sample(3).each do |boardgame| %>
        <%= link_to boardgame_path(boardgame.name) ,class: "link_to" do %>
          <%= render partial: "boardgames/card", locals: { close: false, boardgame: boardgame} %>
        <% end %>
      <% end %>
    </div>
  <% if show_event_creator %>
                   <%# div creator %>
    <%= link_to user_path(event.creator.username), class: "link_to" do %>
      <div class="event-creator ">
        <h4>Proposé par  <%= event.creator.username %></h4>
        <%= cl_image_tag(event.creator.photo.key, class: "avatar-small") %>
      </div>
    <% end %>
                   <%# end %>
  <% end %>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for event do |f| %>
  <%= f.input :title,
              label: "Titre" %>
  <%= f.input :description,
              as: :text %>
  <%= f.input :capacity,
              label: "Nombre de places",
              as: :integer,
              input_html: { min: 1, type: "number" } %>
  <%= f.input :date,
              as: :string,
              input_html: { data: { controller: "datepicker", datepicker_type_value: "event" } } %>
  <%= f.input :time,
              label: "Heure",
              as: :string,
              input_html: { data: { controller: "timepicker" } } %>
  <%= render "map_form", f: f %>

<div class="block-margin">
  <h2>Ajouter des jeux</h2>
</div>

  <div data-controller="autocomplete", class="block-margin">

    <%= f.hidden_field :boardgame_ids, value: "", data: { autocomplete_target: "boardgamesIds"} %> <!-- hidden field to store the boardgame ids -->

    <input type="text" data-autocomplete-target="input" data-action="keyup->autocomplete#search">
    <ul data-autocomplete-target="results", style="list-style-type:none;", id="ul-form">


    </ul>

    <div data-autocomplete-target="selectedBoardgames" class="bg-cards">
      <%# <%= console %>
    </div>
  </div>
<div class="btn-classic block-margin">
  <%= f.button :submit, "Créer l'évènement" %>
</div>
<% end %>

app/views/events/_info_window.html.erb
<h2><%= event.title %></h2>
<p><%= event.address %></p>

app/views/events/_map_form.html.erb
  <%= f.input :address,
    label: "Adresse",
    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
  %>
  <%= f.hidden_field :longitude, data: { address_autocomplete_target: "longitude" } %>
  <%= f.hidden_field :latitude, data: { address_autocomplete_target: "latitude" } %>

app/views/events/_marker.html.erb
<%= image_tag "bgm_logo_v1.png", height: 30, width: 30, alt: "Logo" %>

app/views/events/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.username %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/events/chat.html.erb
<div class="chat">


    <div id="messages" class="messages">
      <% @event.messages.each do |message| %>
        <%= render "events/message", message: message %>
      <% end %>
    </div>
    <div class="input-form">
    <%= simple_form_for [@event, @message], html: {class: "d-flex flex-column"} do |f| %>
      <%= f.input :content,
                  label: false,
                  placeholder: "Votre message",
                  wrapper_html: {class: "flex-grow-1"} %>
      <%= f.submit "Envoyer", class: "btn-submit", data: {controller: :messages, turbo_method: :post } %>
    <% end %>
    </div>
  </div>

app/views/events/index.html.erb
<div class="bgm-container">


  <div class="filter-bar" data-controller="input">

      <%= simple_form_for :search, url: events_path, method: :get, wrapper: :default, html: { class: 'search-form form-inline d-flex mt-3 align-items-center justify-content-center gap-3' } do |f| %>

    <div class="inputs-filter">

        <div class="form-group pb-2">
          <%= f.input :city, label: false, placeholder: "Entrez un lieu", input_html: { class: "search-input form-control" }, required: false %>
        </div>

        <div class="form-group">
          <%= f.input :boardgame, label: false, placeholder: "Entrez un jeu", input_html: { class: "search-input form-control" }, required: false %>
        </div>

    </div>
    <!--  <div class="form-group">
        <%= f.input :date, as: :string, label: false, placeholder: "Sélectionnez une date", input_html: { class: "search-input form-control", data: { controller: "datepicker", input_target: "date" } }, required: false %>
      </div> -->
      <button type="submit" class="btn"><i class="fa-solid fa-magnifying-glass fs-2"></i></button>

    <% end %>

  <!-- <i class="fa-solid fa-calendar" data-input-target="btnCalendar" data-action="click->input#selectDate"></i> -->

  </div>

  <div style="width: 100%; height: 25vh; margin: 20px 0; border-radius: 1.5vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>


  <% if @events.any? %>
    <% @events.each do |event| %>
            <%= render partial: "events/card", locals: { event: event, show_event_creator: true } %>
    <% end %>
  <% end %>
</div>



<%= link_to image_tag("btn_plus.png", class:"btn-action"), new_event_path %>
<div style="padding-bottom: 7vh;"></div>

app/views/events/new.html.erb
<div class="bgm-container">
<div class="block-margin">
  <h2>CRÉER UN ÉVÉNEMENT</h2>
</div>
  <%= render "form", event: @event, boardgames: @boardgames %>
</div>

app/views/events/show.html.erb
  <div class="bgm-container">
<div class="banner-color">
    <div>
      <h1><%= @event.title %></h1>
      <p><%= @event.description %></p>
    </div>
    <div>
      <% if current_user != @event.creator && @event.participants.include?(current_user) == false %>
        <% if user_signed_in? %>
            <div data-controller="toggle">
              <%= link_to "Rejoindre", "#", data: { action: "click->toggle#display" }, class: "btn-banner-color" %>

              <div data-toggle-target="modal" class="modal hidden">
                <div class="modal-content">
                  <span data-action="click->toggle#close" class="close-button">&times;</span>
                  <h2>S'inscrire à l'événement</h2>

                  <%= form_with model: @inscription, url: event_inscriptions_path(@event), local: true do |f| %>
                    <div class="form-inputs">
                      <%= f.text_area :comment, placeholder: "Écrivez un commentaire..." %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                    </div>

                    <div class="form-actions">
                      <%= f.submit "S'inscrire", class: "btn-submit", data: {controller: :inscriptopns, turbo_method: :post } %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
        <% else %>
          <%= link_to "Rejoindre", new_user_session_path, class: "btn-banner-color" %>
        <% end %>

      <% end %>

    </div>
  </div>
</div>
  <div class="bgm-container">
    <%= link_to user_path(@event.creator.username), class: "link_to" do %>
      <div class="event-creator block-margin">
        <%= cl_image_tag(@event.creator.photo.key, class: "avatar") %>
        <p>Proposé par</p>
        <p><%= @event.creator.username %></p>
      </div>
    <% end %>
    <h2>Les jeux proposés</h2>
    <div class="bg-cards block-margin">
    <% @event.boardgames.each do |boardgame| %>
      <%= link_to boardgame_path(boardgame.name) ,class: "link_to" do %>
        <%= render partial: "boardgames/card", locals: { close: false, boardgame: boardgame} %>
      <% end %>
    <% end %>

  </div>



  <h2>Informations</h2>

  <div class="infos block-margin">
    <p>Date : <%= @event.date %></p>
    <p>Lieu : <%= @event.city %></p>
    <p>Places : <%= @event.capacity %></p>
  </div>

  <h2>Participants</h2>

  <% if @event.participants.present? %>
    <div class="participant-cards block-margin">
        <% @event.participants.each do |participant| %>
          <%= link_to user_path(participant.username) do %>
            <%= cl_image_tag(participant.photo.key, class: "avatar") %>
          <% end %>
        <% end %>
  <% else %>
        <p>Aucun participant pour le moment</p>
  <% end %>
    </div>

  <% if current_user == @event.creator || @event.users.include?(current_user) %>
    <%= link_to image_tag("btn_chat.png", class:"btn-action"), chat_path %>
  <% end %>


</div>